[project]
name = "ae-pytorch"
version = "0.1.0"
description = "A repository for implementations of a variety of VAE's along with useful documentation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.9.0",
    "torchaudio>=2.9.0",
    "torchvision>=0.24.0",
]
